// //src/app/layout.tsx
// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import AppSidebar from "@/components/app-sidebar";
// import { ThemeProvider } from "next-themes";
// import "./globals.css";
// import { ScrollArea } from "@/components/ui/scroll-area";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <ThemeProvider
//           attribute="class"
//           defaultTheme="system"
//           enableSystem
//           disableTransitionOnChange
//         >
//           {/* Responsive grid layout with sidebar and main content */}
//           <div className="mx-auto grid min-h-screen max-w-7xl px-4 lg:grid-cols-[16rem_1fr] lg:px-12">
//             {/* Sidebar (hidden on mobile) */}
//             <aside className="hidden border-r border-zinc-200 lg:block dark:border-zinc-800">
//               <AppSidebar />
//             </aside>

//             {/* Main Content */}
//             <main className="w-full overflow-x-hidden">
//               <div className="aos-init aos-animate mt-20 p-8 lg:mt-0">
//                 <ScrollArea>{children}</ScrollArea>
//               </div>
//             </main>
//           </div>
//         </ThemeProvider>
//       </body>
//     </html>
//   );
// }

// src/app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import AppSidebar from "@/components/app-sidebar";
import { ThemeProvider } from "next-themes";
import { ScrollArea } from "@/components/ui/scroll-area";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My Portfolio",
  description: "Sophonwit Thapseng Portfolio Site",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} font-sans antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="mx-auto grid min-h-screen max-w-7xl grid-cols-1 px-4 lg:grid-cols-[16rem_1fr] lg:px-12">
            {/* Sidebar */}
            <aside className="hidden border-r border-zinc-200 lg:block dark:border-zinc-800">
              <AppSidebar />
            </aside>

            {/* Main Content */}
            <main className="h-screen overflow-hidden">
              <ScrollArea className="h-full w-full">
                <div className="mt-20 p-8 lg:mt-0">{children}</div>
              </ScrollArea>
            </main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
